site_name: FDU经验录
site_description: Survive in FDU 经验传承
site_author: AlanBook

theme:
    name: material
    features:
        #- navigation.tabs
        #- navigation.tabs.sticky
        - navigation.top
        #- navigation.footer
        - navigation.tracking
        - navigation.expand
        - header.autohide

        - search.suggest
        - search.highlight
        - search.share

        #- toc.integrate
        - toc.follow
        - content.tabs.link
        #- content.code.annotate
        #- content.code.copy
    langauge: zh
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
           icon: material/brightness-7
           name: Switch to dark mode
        accent: deep orange
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
           icon: material/brightness-4
           name: Switch to light mode
        accent: lime
    icon:
      repo: fontawesome/brands/git-alt
    #font:
    #  text: Noto Serif Simplified Chinese

extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/AlanBook
    #alternate:
      #- name: 简体中文
      #  link: /zh/
      #  lang: zh
      #- name: English
      #  link: /en/
      #  lang: en
    analytics:
      feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="..." target="_blank" rel="noopener">feedback form</a>.


copyright:
  Copyright © 2023 <a href="https://github.com/AlanBook" target="_blank" rel="noopener">AlanBook</a>
        
repo_url: https://github.com/AlanBook/fdu-lessons-set
repo_name: AlanBook/fdu-lessons-set

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      title: 本页目录


nav:
  - 前言: "index.md"
  - Fdu大一新生 部分指南: "freshman.md"
  - 社政:
      - 社政分团委学生会
      - 学术发展部: "社政/xuefa.md"
  - 经验传承:
      - 出行游逛: "出行游逛/tours.md"